spring:
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
