DROP TABLE IF EXISTS user;

CREATE TABLE user  (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(250) NOT NULL,
  Family VARCHAR(250) NOT NULL,
  User_Name VARCHAR(250) NOT NULL,
  Salary DECIMAL(10, 2) DEFAULT NULL
);

INSERT INTO user (Name, Family, User_Name, Salary) VALUES
  ('Test', 'Test', 'TestUN', 10000 );
